### ISSUE TITLE
Use Withings Data API

### ISSUE THREAD

**Issue by ololobus** [dhayab/homebridge-withings-air-quality#15]
Probably one can use Withings Data API instead of direct usage of login/pass: https://developer.withings.com/oauth2/#section/Data-API

For example, register your own app and provide only a token for your plugin. What do you think?

**Comment by dhayab** [comment]
Hi, as [commented here](https://github.com/dhayab/homebridge-withings-air-quality/issues/6#issuecomment-627754670), I can't use the official OAuth2 API, since they don't expose the carbon dioxide levels there.
