### ISSUE TITLE
Seems like

### ISSUE THREAD

**Issue by ofb72** [dhayab/homebridge-withings-air-quality#17]
The plug-in will not be enhanced … sadly

**Comment by alert82** [comment]
yip looks like :-(

**Comment by dhayab** [comment]
Hi, this plugin is not actively maintained anymore. You'll [find here](https://github.com/dhayab/homebridge-withings-air-quality/issues/6#issuecomment-866282357) some things that could be done to make the plugin more stable, and I'll gladly accept any pull request that helps in this way.

For the time being, I'll close this issue.
