### ISSUE TITLE
Cannot read property 'date' of undefined

### ISSUE THREAD

**Issue by marmitol** [dhayab/homebridge-withings-air-quality#7]
Hello.

The log shows this error.

Withings Air Quality] Could not fetch data from API / Cannot read property 'date' of undefined.

How can we make the data update frequency more frequent? Now the update frequency can be up to 24 hours. The data you display is not current.

Thank you very much.

**Comment by dhayab** [comment]
Hi,

The API used to retrieve the data needed by the plugin is unstable and sometimes it fails to return values that are expected in the code.

The smart scale, being a low-powered device, sends its data to the server at most twice a day in batch (less if you don’t wake it by using it). The plugin gets the latest data available from the API every 15 minutes.

**Comment by marmitol** [comment]
Okay.

What a quick response.
I got it, thanks a lot.
